const APP_VERSION="26.26.1";
const APP_REVISION="senha-administrativa-r47";
const CACHE_NAME="nexlab-v26-26-1-shell-r47";
const RUNTIME_CACHE="nexlab-v26-26-1-runtime-r47";
const IMAGE_CACHE="nexlab-v26-26-1-images-r47";
const SHELL_FILES=["./","./index.html","./offline.html","./404.html","./homologacao.html","./prontidao.html","./release.json","./manifest.webmanifest?v=brand-r38","./assets/index-R45v26251.js?v=app-r26251-update-auto-r45","./assets/index-B1u8eynw.css?v=brand-r38","./assets/nexlab-bootstrap.js?v=app-r26251-update-auto-r45","./assets/nexlab-visual.css?v=app-r26251-update-auto-r45","./assets/nexlab-update-manager.js?v=app-r26251-update-auto-r45","./assets/nexlab-visual.js?v=app-r26251-update-auto-r45","./assets/nexlab-permissions-phase2.css?v=app-r26261-password-r47","./assets/nexlab-permissions-phase2.js?v=app-r26261-password-r47","./icons/nexlab-192.png?v=brand-r38","./icons/nexlab-512.png?v=brand-r38","./icons/nexlab-maskable-192.png?v=brand-r38","./icons/nexlab-maskable-512.png?v=brand-r38","./icons/apple-touch-icon.png?v=brand-r38","./icons/nexlab-favicon-rounded.png?v=brand-r38","./brand/nexlab-logo-light.webp?v=brand-r38","./brand/nexlab-logo-dark.webp?v=brand-r38","./brand/nexlab-icon.webp?v=brand-r38"];
const ALLOWED_TABS=new Set(["dashboard","pendencias","agenda","notificacoes","participantes","permissoes","equipes","perfil","projetos","patrimonio","estoque","reserva","marketing","eventos","mural","feedback","relatorios","saude-sistema","logs"]);
async function notifyClients(message){const windows=await self.clients.matchAll({type:"window",includeUncontrolled:true});windows.forEach(c=>c.postMessage(message))}
function injectPhase2(html){if(html.includes('nexlab-permissions-phase2.js'))return html;const payload=`<script>document.querySelector('meta[name="nexlab-version"]')?.setAttribute('content','26.26.1');document.documentElement.dataset.nexlabVersion='26.26.1';</script><link rel="stylesheet" href="./assets/nexlab-permissions-phase2.css?v=app-r26261-password-r47"><script defer src="./assets/nexlab-permissions-phase2.js?v=app-r26261-password-r47"></script>`;return html.replace(/<head([^>]*)>/i,`<head$1>${payload}`)}
async function transformHtml(response){if(!response)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;const html=injectPhase2(await response.text());const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=utf-8');return new Response(html,{status:response.status,statusText:response.statusText,headers})}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);await cache.addAll(SHELL_FILES);if(!self.registration.active){await self.skipWaiting();return}await notifyClients({type:'NEXLAB_UPDATE_READY',version:APP_VERSION,revision:APP_REVISION,cache:CACHE_NAME})})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>![CACHE_NAME,RUNTIME_CACHE,IMAGE_CACHE].includes(k)).map(k=>caches.delete(k)));await self.clients.claim();await notifyClients({type:'NEXLAB_UPDATE_ACTIVATED',version:APP_VERSION,revision:APP_REVISION,cache:CACHE_NAME})})()));
async function navigation(request){try{const fresh=await fetch(request,{cache:'no-store'});if(!fresh.ok)throw new Error('navigation');const transformed=await transformHtml(fresh);const cache=await caches.open(RUNTIME_CACHE);cache.put(request,transformed.clone()).catch(()=>{});return transformed}catch{const cached=await caches.match(request,{ignoreSearch:true})||await caches.match('./index.html')||await caches.match('./offline.html');return transformHtml(cached)}}
async function release(request){try{const response=await fetch(new Request(request,{cache:'no-store'}));if(!response.ok)throw new Error();const cache=await caches.open(CACHE_NAME);cache.put('./release.json',response.clone()).catch(()=>{});return response}catch{return await caches.match('./release.json')||new Response('{}',{status:503,headers:{'Content-Type':'application/json'}})}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response?.ok){const cache=await caches.open(request.destination==='image'?IMAGE_CACHE:RUNTIME_CACHE);cache.put(request,response.clone()).catch(()=>{})}return response}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith('/release.json'))return event.respondWith(release(event.request));if(event.request.mode==='navigate')return event.respondWith(navigation(event.request));if(['script','style','image','font','manifest'].includes(event.request.destination))return event.respondWith(cacheFirst(event.request));event.respondWith(fetch(event.request).catch(()=>caches.match(event.request)))});
self.addEventListener('message',event=>{if(event.data?.type==='NEXLAB_SKIP_WAITING')event.waitUntil(self.skipWaiting());if(event.data?.type==='NEXLAB_GET_VERSION')event.ports?.[0]?.postMessage({type:'NEXLAB_VERSION',version:APP_VERSION,revision:APP_REVISION,cache:CACHE_NAME})});
self.addEventListener('push',event=>{let p={};try{p=event.data?event.data.json():{}}catch{p={body:event.data?.text()}}const requested=String(p?.data?.targetTab||'notificacoes'),targetTab=ALLOWED_TABS.has(requested)?requested:'notificacoes';event.waitUntil(self.registration.showNotification(String(p.title||'NEXLAB').slice(0,120),{body:String(p.body||'Você recebeu uma nova notificação.').slice(0,500),icon:'./icons/nexlab-192.png?v=brand-r38',badge:'./icons/nexlab-192.png?v=brand-r38',tag:String(p.tag||`nexlab-${Date.now()}`).slice(0,160),data:{targetTab}}))});
self.addEventListener('notificationclick',event=>{event.notification.close();const requested=String(event.notification?.data?.targetTab||'notificacoes'),tab=ALLOWED_TABS.has(requested)?requested:'notificacoes',url=new URL('./',self.location.href);url.searchParams.set('nexlabTab',tab);event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(async clients=>{for(const client of clients){client.postMessage({type:'NEXLAB_NAVIGATE',tab});await client.focus();return}return self.clients.openWindow?.(url.toString())}))});
